name: Inscription

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  inscribe:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Pull Repo
      run: |
        git pull

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 scripts/process_v2.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'haoboch'
        git config --global user.email 'usappzyh@gmail.com'
        git add .
        git commit -m "Update inscription list"
        git push
